all: allfs 

clean:
	rm -fr *.o 

allfs: test_mmap_read test_mmap_write

xattr:
	@echo "Nothing to build for xattr"

pynfs40:
	@echo "Nothing to build for pynfs40"

pynfs41:
	@echo "Nothing to build for pynfs41"



